version: "2"
run:
  tests: true
  allow-parallel-runners: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - asciicheck
    - bidichk
    - contextcheck
    - decorder
    - durationcheck
    - errorlint
    - gochecknoglobals
    - goconst
    - godot
    - gosec
    - lll
    - nakedret
    - nilerr
    - staticcheck
    - testpackage
    - unused
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gochecknoglobals
          - testpackage
        path: export.*_test\.go
      - linters:
          - unparam
          - unused
        path: benchmarks/*
      - linters:
          - errcheck
        text: .AbortWithReason
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/xconnio)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
